// Generated by CoffeeScript 1.10.0
var DateField, doExport,
  hasProp = {}.hasOwnProperty;

Translator.fieldMap = {
  place: {
    name: 'location',
    enc: 'literal'
  },
  chapter: {
    name: 'chapter'
  },
  edition: {
    name: 'edition'
  },
  title: {
    name: 'title',
    autoCase: true
  },
  volume: {
    name: 'volume'
  },
  rights: {
    name: 'rights'
  },
  ISBN: {
    name: 'isbn'
  },
  ISSN: {
    name: 'issn'
  },
  url: {
    name: 'url'
  },
  DOI: {
    name: 'doi'
  },
  shortTitle: {
    name: 'shorttitle',
    autoCase: true
  },
  abstractNote: {
    name: 'abstract'
  },
  numberOfVolumes: {
    name: 'volumes'
  },
  versionNumber: {
    name: 'version'
  },
  conferenceName: {
    name: 'eventtitle'
  },
  numPages: {
    name: 'pagetotal'
  },
  type: {
    name: 'type'
  }
};

Translator.typeMap = {
  'book booklet manual proceedings': 'book',
  'incollection inbook': 'bookSection',
  'article misc': 'journalArticle magazineArticle newspaperArticle',
  thesis: 'thesis',
  letter: 'email letter',
  movie: 'film',
  artwork: 'artwork',
  '=online': 'blogPost forumPost webpage',
  inproceedings: 'conferencePaper',
  report: 'report',
  legislation: 'statute bill',
  jurisdiction: 'case hearing',
  patent: 'patent',
  audio: 'audioRecording podcast radioBroadcast',
  video: 'videoRecording tvBroadcast',
  software: 'computerProgram',
  unpublished: 'manuscript presentation',
  inreference: 'encyclopediaArticle dictionaryEntry',
  misc: 'interview map instantMessage document'
};

Translator.fieldEncoding = {
  url: 'url',
  doi: 'verbatim',
  eprint: 'verbatim',
  eprintclass: 'verbatim',
  crossref: 'raw',
  xdata: 'raw',
  xref: 'raw',
  entrykey: 'raw',
  childentrykey: 'raw',
  verba: 'verbatim',
  verbb: 'verbatim',
  verbc: 'verbatim'
};

DateField = (function() {
  function DateField(date, locale, formatted, literal) {
    var parsed;
    parsed = Zotero.BetterBibTeX.parseDateToObject(date, locale);
    switch (false) {
      case !!parsed:
        this.field = {};
        break;
      case !parsed.literal:
        this.field = {
          name: literal,
          value: date
        };
        break;
      case !((parsed.year || parsed.empty) && (parsed.year_end || parsed.empty_end)):
        this.field = {
          name: formatted,
          value: this.format(parsed) + '/' + this.format(parsed, '_end')
        };
        break;
      case !parsed.year:
        this.field = {
          name: formatted,
          value: this.format(parsed)
        };
        break;
      default:
        this.field = {};
    }
  }

  DateField.prototype.pad = function(v, pad) {
    if (v.length >= pad.length) {
      return v;
    }
    return (pad + v).slice(-pad.length);
  };

  DateField.prototype.format = function(v, suffix) {
    var _v, f, i, len, ref1;
    if (suffix == null) {
      suffix = '';
    }
    _v = {};
    ref1 = ['empty', 'year', 'month', 'day'];
    for (i = 0, len = ref1.length; i < len; i++) {
      f = ref1[i];
      _v[f] = v["" + f + suffix];
    }
    if (_v.empty) {
      return '';
    }
    if (_v.year && _v.month && _v.day) {
      return _v.year + "-" + (this.pad(_v.month, '00')) + "-" + (this.pad(_v.day, '00'));
    }
    if (_v.year && _v.month) {
      return _v.year + "-" + (this.pad(_v.month, '00'));
    }
    return '' + _v.year;
  };

  return DateField;

})();

doExport = function() {
  var abbr, archive, creator, creators, eprinttype, field, i, item, j, k, len, len1, len2, m, name, note, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref16, ref17, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, thesistype, value;
  Zotero.write('\n');
  while (item = Translator.nextItem()) {
    ref = new Reference(item);
    if (item.itemType === 'bookSection' && ref.hasCreator('bookAuthor')) {
      ref.referencetype = 'inbook';
    }
    if (item.itemType === 'book' && !ref.hasCreator('author') && ref.hasCreator('editor')) {
      ref.referencetype = 'collection';
    }
    if (ref.referencetype === 'book' && item.numberOfVolumes) {
      ref.referencetype = 'mvbook';
    }
    if (m = (ref1 = item.publicationTitle) != null ? ref1.match(/^arxiv:\s*([\S]+)/i) : void 0) {
      ref.add({
        name: 'eprinttype',
        value: 'arxiv'
      });
      ref.add({
        name: 'eprint',
        value: m[1]
      });
      delete item.publicationTitle;
    }
    if (m = (ref2 = item.url) != null ? ref2.match(/^http:\/\/www.jstor.org\/stable\/([\S]+)$/i) : void 0) {
      ref.add({
        name: 'eprinttype',
        value: 'jstor'
      });
      ref.add({
        name: 'eprint',
        value: m[1]
      });
      delete item.url;
      ref.remove('url');
    }
    if (m = (ref3 = item.url) != null ? ref3.match(/^http:\/\/books.google.com\/books?id=([\S]+)$/i) : void 0) {
      ref.add({
        name: 'eprinttype',
        value: 'googlebooks'
      });
      ref.add({
        name: 'eprint',
        value: m[1]
      });
      delete item.url;
      ref.remove('url');
    }
    if (m = (ref4 = item.url) != null ? ref4.match(/^http:\/\/www.ncbi.nlm.nih.gov\/pubmed\/([\S]+)$/i) : void 0) {
      ref.add({
        name: 'eprinttype',
        value: 'pubmed'
      });
      ref.add({
        name: 'eprint',
        value: m[1]
      });
      delete item.url;
      ref.remove('url');
    }
    ref5 = ['pmid', 'arxiv', 'jstor', 'hdl', 'googlebooks'];
    for (i = 0, len = ref5.length; i < len; i++) {
      eprinttype = ref5[i];
      if (ref.has[eprinttype]) {
        if (!ref.has.eprinttype) {
          ref.add({
            name: 'eprinttype',
            value: eprinttype
          });
          ref.add({
            name: 'eprint',
            value: ref.has[eprinttype].value
          });
        }
        ref.remove(eprinttype);
      }
    }
    if (item.archive && item.archiveLocation) {
      archive = true;
      switch (item.archive.toLowerCase()) {
        case 'arxiv':
          if (!ref.has.eprinttype) {
            ref.add({
              name: 'eprinttype',
              value: 'arxiv'
            });
          }
          ref.add({
            name: 'eprintclass',
            value: item.callNumber
          });
          break;
        case 'jstor':
          if (!ref.has.eprinttype) {
            ref.add({
              name: 'eprinttype',
              value: 'jstor'
            });
          }
          break;
        case 'pubmed':
          if (!ref.has.eprinttype) {
            ref.add({
              name: 'eprinttype',
              value: 'pubmed'
            });
          }
          break;
        case 'hdl':
          if (!ref.has.eprinttype) {
            ref.add({
              name: 'eprinttype',
              value: 'hdl'
            });
          }
          break;
        case 'googlebooks':
        case 'google books':
          if (!ref.has.eprinttype) {
            ref.add({
              name: 'eprinttype',
              value: 'googlebooks'
            });
          }
          break;
        default:
          archive = false;
      }
      if (archive) {
        if (!ref.has.eprint) {
          ref.add({
            name: 'eprint',
            value: item.archiveLocation
          });
        }
      }
    }
    ref.add({
      name: 'langid',
      value: ref.language
    });
    ref.add({
      name: 'number',
      value: item.docketNumber || item.publicLawNumber || item.reportNumber || item.seriesNumber || item.patentNumber || item.billNumber || item.episodeNumber || item.number
    });
    ref.add({
      name: (isNaN(parseInt(item.issue)) ? 'issue' : 'number'),
      value: item.issue
    });
    switch (item.itemType) {
      case 'case':
      case 'gazette':
        ref.add({
          name: 'journaltitle',
          value: item.reporter,
          preserveBibTeXVariables: true
        });
        break;
      case 'statute':
        ref.add({
          name: 'journaltitle',
          value: item.code,
          preserveBibTeXVariables: true
        });
    }
    if (item.publicationTitle) {
      switch (item.itemType) {
        case 'bookSection':
        case 'conferencePaper':
        case 'dictionaryEntry':
        case 'encyclopediaArticle':
          ref.add({
            name: 'booktitle',
            value: item.bookTitle || item.publicationTitle,
            preserveBibTeXVariables: true,
            autoCase: true
          });
          break;
        case 'magazineArticle':
        case 'newspaperArticle':
          ref.add({
            name: 'journaltitle',
            value: item.publicationTitle,
            preserveBibTeXVariables: true
          });
          if (item.itemType === 'newspaperArticle') {
            ref.add({
              name: 'journalsubtitle',
              value: item.section
            });
          }
          break;
        case 'journalArticle':
          if (ref.isBibVar(item.publicationTitle)) {
            ref.add({
              name: 'journaltitle',
              value: item.publicationTitle,
              preserveBibTeXVariables: true
            });
          } else {
            abbr = Zotero.BetterBibTeX.keymanager.journalAbbrev(item);
            if (Translator.useJournalAbbreviation && abbr) {
              ref.add({
                name: 'journal',
                value: abbr,
                preserveBibTeXVariables: true
              });
            } else {
              ref.add({
                name: 'journaltitle',
                value: item.publicationTitle,
                preserveBibTeXVariables: true
              });
              ref.add({
                name: 'shortjournal',
                value: abbr,
                preserveBibTeXVariables: true
              });
            }
          }
      }
    }
    if (!ref.has.booktitle) {
      ref.add({
        name: 'booktitle',
        value: item.bookTitle || item.encyclopediaTitle || item.dictionaryTitle || item.proceedingsTitle,
        autoCase: true
      });
    }
    ref.add({
      name: ((ref6 = ref.referencetype) === 'movie' || ref6 === 'video' ? 'booktitle' : 'titleaddon'),
      value: item.websiteTitle || item.forumTitle || item.blogTitle || item.programTitle,
      autoCase: (ref7 = ref.referencetype) === 'movie' || ref7 === 'video'
    });
    ref.add({
      name: 'series',
      value: item.seriesTitle || item.series
    });
    switch (item.itemType) {
      case 'report':
      case 'thesis':
        ref.add({
          name: 'institution',
          value: item.institution || item.publisher || item.university,
          enc: 'literal'
        });
        break;
      case 'case':
      case 'hearing':
        ref.add({
          name: 'institution',
          value: item.court,
          enc: 'literal'
        });
        break;
      default:
        ref.add({
          name: 'publisher',
          value: item.publisher,
          enc: 'literal'
        });
    }
    switch (item.itemType) {
      case 'letter':
        ref.add({
          name: 'type',
          value: item.letterType || 'Letter',
          replace: true
        });
        break;
      case 'email':
        ref.add({
          name: 'type',
          value: 'E-mail',
          replace: true
        });
        break;
      case 'thesis':
        thesistype = (ref8 = item.thesisType) != null ? ref8.toLowerCase() : void 0;
        if (thesistype === 'phdthesis' || thesistype === 'mastersthesis') {
          ref.referencetype = thesistype;
          ref.remove('type');
        } else {
          ref.add({
            name: 'type',
            value: item.thesisType,
            replace: true
          });
        }
        break;
      case 'report':
        if ((item.type || '').toLowerCase().trim() === 'techreport') {
          ref.referencetype = 'techreport';
        } else {
          ref.add({
            name: 'type',
            value: item.type,
            replace: true
          });
        }
        break;
      default:
        ref.add({
          name: 'type',
          value: item.type || item.websiteType || item.manuscriptType,
          replace: true
        });
    }
    ref.add({
      name: 'howpublished',
      value: item.presentationType || item.manuscriptType
    });
    ref.add({
      name: 'note',
      value: item.meetingName,
      allowDuplicates: true
    });
    if (item.creators && item.creators.length) {
      creators = {
        author: [],
        bookauthor: [],
        commentator: [],
        editor: [],
        editora: [],
        editorb: [],
        holder: [],
        translator: [],
        scriptwriter: [],
        director: []
      };
      ref9 = item.creators;
      for (j = 0, len1 = ref9.length; j < len1; j++) {
        creator = ref9[j];
        switch (creator.creatorType) {
          case 'director':
            if ((ref10 = ref.referencetype) === 'video' || ref10 === 'movie') {
              creators.director.push(creator);
            } else {
              creators.author.push(creator);
            }
            break;
          case 'author':
          case 'interviewer':
          case 'programmer':
          case 'artist':
          case 'podcaster':
          case 'presenter':
            creators.author.push(creator);
            break;
          case 'bookAuthor':
            creators.bookauthor.push(creator);
            break;
          case 'commenter':
            creators.commentator.push(creator);
            break;
          case 'editor':
            creators.editor.push(creator);
            break;
          case 'inventor':
            creators.holder.push(creator);
            break;
          case 'translator':
            creators.translator.push(creator);
            break;
          case 'seriesEditor':
            creators.editorb.push(creator);
            break;
          case 'scriptwriter':
            if ((ref11 = ref.referencetype) === 'video' || ref11 === 'movie') {
              creators.scriptwriter.push(creator);
            } else {
              creators.editora.push(creator);
            }
            break;
          default:
            creators.editora.push(creator);
        }
      }
      for (field in creators) {
        if (!hasProp.call(creators, field)) continue;
        value = creators[field];
        ref.add({
          name: field,
          value: value,
          enc: 'creators'
        });
      }
      if (creators.editora.length > 0) {
        ref.add({
          name: 'editoratype',
          value: 'collaborator'
        });
      }
      if (creators.editorb.length > 0) {
        ref.add({
          name: 'editorbtype',
          value: 'redactor'
        });
      }
    }
    if (item.accessDate && item.url) {
      ref.add({
        name: 'urldate',
        value: Zotero.Utilities.strToISO(item.accessDate)
      });
    }
    ref.add((new DateField(item.date, item.language, 'date', 'year')).field);
    switch (false) {
      case !item.pages:
        ref.add({
          name: 'pages',
          value: item.pages.replace(/[-\u2012-\u2015\u2053]+/g, '--')
        });
        break;
      case !(item.firstPage && item.lastPage):
        ref.add({
          name: 'pages',
          value: item.firstPage + "--" + item.lastPage
        });
        break;
      case !item.firstPage:
        ref.add({
          name: 'pages',
          value: "" + item.firstPage
        });
    }
    ref.add({
      name: (ref.has.note ? 'annotation' : 'note'),
      value: item.extra,
      allowDuplicates: true
    });
    ref.add({
      name: 'keywords',
      value: item.tags,
      enc: 'tags'
    });
    if (item.notes && Translator.exportNotes) {
      ref12 = item.notes;
      for (k = 0, len2 = ref12.length; k < len2; k++) {
        note = ref12[k];
        ref.add({
          name: 'annotation',
          value: Zotero.Utilities.unescapeHTML(note.note),
          allowDuplicates: true
        });
      }
    }
    if (ref.useprefix) {
      ref.add({
        name: 'options',
        value: 'useprefix=true'
      });
    }
    ref.add({
      name: 'file',
      value: item.attachments,
      enc: 'attachments'
    });
    ref13 = ref.override;
    for (name in ref13) {
      if (!hasProp.call(ref13, name)) continue;
      value = ref13[name];
      if (value.format !== 'csl') {
        continue;
      }
      switch (false) {
        case !(name === 'volume-title' && ref.item.itemType === 'book' && ref.has.title):
          ref.add({
            name: 'maintitle',
            value: value.value,
            autoCase: true
          });
          ref14 = [ref.has.maintitle.bibtex, ref.has.title.bibtex], ref.has.title.bibtex = ref14[0], ref.has.maintitle.bibtex = ref14[1];
          ref15 = [ref.has.maintitle.value, ref.has.title.value], ref.has.title.value = ref15[0], ref.has.maintitle.value = ref15[1];
          break;
        case !(name === 'volume-title' && ref.item.itemType === 'bookSection' && ref.has.booktitle):
          ref.add({
            name: 'maintitle',
            value: value.value,
            autoCase: true
          });
          ref16 = [ref.has.maintitle.bibtex, ref.has.booktitle.bibtex], ref.has.booktitle.bibtex = ref16[0], ref.has.maintitle.bibtex = ref16[1];
          ref17 = [ref.has.maintitle.value, ref.has.booktitle.value], ref.has.booktitle.value = ref17[0], ref.has.maintitle.value = ref17[1];
          break;
        default:
          continue;
      }
      delete ref.override[name];
    }
    ref.complete();
  }
  Translator.exportGroups();
  Zotero.write('\n');
};
