// Generated by CoffeeScript 1.10.0
var detectImport, doImport;

detectImport = function() {
  var aux, str;
  aux = '';
  while ((str = Zotero.read(0x100000)) !== false) {
    aux += str;
  }
  return aux.match(/\\citation{/);
};

doImport = function() {
  var aux, data, item, m, re, str;
  aux = '';
  while ((str = Zotero.read(0x100000)) !== false) {
    aux += str;
  }
  data = {
    translator: Translator.header.translatorID,
    citations: Object.create(null)
  };
  re = /\\citation{([^}]+)}/g;
  while (m = re.exec(aux)) {
    data.citations[m[1]] = m[1];
  }
  data.citations = Object.keys(data.citations);
  data.citations.sort(function(a, b) {
    return a.localeCompare(b, void 0, {
      sensitivity: 'base'
    });
  });
  item = new Zotero.Item('journalArticle');
  item.title = Translator.header.label;
  item.extra = JSON.stringify(data);
  item.complete();
  Translator.log('::: imported', item);
};
