// Generated by CoffeeScript 1.10.0
var doExport;

doExport = function() {
  var item, keys;
  keys = [];
  while (item = Translator.nextItem()) {
    keys.push("@" + item.__citekey__);
  }
  Zotero.write(keys.join('; '));
};
