# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 2180);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20151029151421");
user_pref("browser.startup.homepage_override.mstone", "42.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "308046B0AF4A39CB");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.usedOnWindows10", true);
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1448617778465");
user_pref("datareporting.policy.firstRunTime", "1448531378465");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1408);
user_pref("datareporting.sessions.current.main", 23);
user_pref("datareporting.sessions.current.sessionRestored", 2190);
user_pref("datareporting.sessions.current.startTime", "1448531378106");
user_pref("datareporting.sessions.current.totalTime", 18);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-yqAChkhrLgaY2g@jetpack\":{\"version\":\"0.1\",\"type\":\"extension\",\"descriptor\":\"e:\\\\kuaipan\\\\addon-sdk-1.17\\\\bin\\\\BBT\\\\ffdebug\\\\extensions\\\\jid1-yqAChkhrLgaY2g@jetpack.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.checkCompatibility.42.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:42.0");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "42.0");
user_pref("extensions.lastPlatformVersion", "42.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk.console.logLevel", "info");
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("extensions.xpiState", "{\"app-profile\":{\"jid1-yqAChkhrLgaY2g@jetpack\":{\"d\":\"e:\\\\kuaipan\\\\addon-sdk-1.17\\\\bin\\\\BBT\\\\ffdebug\\\\extensions\\\\jid1-yqAChkhrLgaY2g@jetpack.xpi\",\"e\":true,\"v\":\"0.1\",\"st\":1448531378054}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"42.0\",\"st\":1447674687600,\"mt\":1446163994000}}}");
user_pref("gecko.buildID", "20151029151421");
user_pref("gecko.mstone", "42.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 1);
user_pref("gfx.driver-init.appVersion", "42.0");
user_pref("gfx.driver-init.deviceID", "0x042f");
user_pref("gfx.driver-init.driverVersion", "9.18.13.4135");
user_pref("gfx.driver-init.feature-d2d", true);
user_pref("gfx.driver-init.feature-d3d11", true);
user_pref("gfx.driver-init.status", 2);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("sanity-test.device-id", "0x042f");
user_pref("sanity-test.driver-version", "9.18.13.4135");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "42.0");
user_pref("signon.importedFromSqlite", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1448531378);
user_pref("toolkit.telemetry.previousBuildID", "20151029151421");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("urlclassifier.updateinterval", 172800);
