// Generated by CoffeeScript 1.10.0
var BBTCoherentExportOptions;

BBTCoherentExportOptions = function(e) {
  var i, len, node, ref;
  ref = document.getElementById('translator-options').children;
  for (i = 0, len = ref.length; i < len; i++) {
    node = ref[i];
    switch (node.id) {
      case 'export-option-exportFileData':
        if (e.target.id === node.id && node.checked) {
          document.getElementById('export-option-Keep updated').checked = false;
        }
        break;
      case 'export-option-Keep updated':
        if (e.target.id === node.id && node.checked) {
          document.getElementById('export-option-exportFileData').checked = false;
        }
    }
  }
};

Zotero_File_Interface_Export.init = (function(original) {
  return function() {
    var i, len, node, r, ref;
    r = original.apply(this, arguments);
    ref = document.getElementById('translator-options').children;
    for (i = 0, len = ref.length; i < len; i++) {
      node = ref[i];
      if (node.id.indexOf('export-option-') !== 0) {
        continue;
      }
      switch (node.id) {
        case 'export-option-exportFileData':
        case 'export-option-Keep updated':
          if (!node.getAttribute('better-bibtex')) {
            node.setAttribute('better-bibtex', 'true');
            node.addEventListener('command', BBTCoherentExportOptions);
          }
          if (node.id === 'export-option-Keep updated') {
            node.checked = false;
          }
      }
    }
    return r;
  };
})(Zotero_File_Interface_Export.init);
