// Generated by CoffeeScript 1.10.0
var i, len, load, loader, ref, script;

if (!Zotero.BetterBibTeX) {
  loader = Components.classes['@mozilla.org/moz/jssubscript-loader;1'].getService(Components.interfaces.mozIJSSubScriptLoader);
  ref = " lokijs zotero-better-bibtex release db csl-localedata fold-to-ascii punycode BetterBibTeXPatternFormatter BetterBibTeXPatternParser preferences keymanager web-endpoints schomd cayw debug-bridge cache autoexport serialized".trim().split(/\s+/);
  for (i = 0, len = ref.length; i < len; i++) {
    script = ref[i];
    Zotero.debug('BBT: ' + script);
    loader.loadSubScript("chrome://zotero-better-bibtex/content/" + script + ".js");
  }
  window.addEventListener('load', (load = function(event) {
    window.removeEventListener('load', load, false);
    Zotero.BetterBibTeX.init();
  }), false);
}
