// Generated by CoffeeScript 1.10.0
window.addEventListener('load', function() {
  var observer;
  ZoteroItemPane.addCitekeyRow();
  observer = new MutationObserver(function(mutations) {
    var i, len, mutation, results;
    results = [];
    for (i = 0, len = mutations.length; i < len; i++) {
      mutation = mutations[i];
      if (mutation.target.childNodes.length === 1) {
        results.push(ZoteroItemPane.addCitekeyRow());
      } else {
        results.push(void 0);
      }
    }
    return results;
  });
  observer.observe(document.getElementById('dynamic-fields'), {
    childList: true
  });
});

ZoteroItemPane.addCitekeyRow = function() {
  var fields, id, label, row, template, value;
  id = 'zotero-better-bibtex-itempane-citekey';
  if (document.getElementById(id)) {
    return;
  }
  template = document.getElementById('zotero-better-bibtex-itempane-citekey-template');
  label = template.firstElementChild.cloneNode(true);
  value = template.lastElementChild.cloneNode(true);
  value.id = 'zotero-better-bibtex-itempane-citekey';
  row = document.createElement('row');
  row.appendChild(label);
  row.appendChild(value);
  fields = document.getElementById('dynamic-fields');
  if (fields.childNodes.length > 1) {
    return fields.insertBefore(row, fields.childNodes[1]);
  } else {
    return fields.appendChild(row);
  }
};

ZoteroItemPane.viewItem = (function(original) {
  return function(item, mode, index) {
    var citekey, display;
    original.apply(this, arguments);
    if (index === 0) {
      ZoteroItemPane.addCitekeyRow();
      display = document.getElementById('zotero-better-bibtex-itempane-citekey');
      citekey = Zotero.BetterBibTeX.keymanager.get(item);
      if (citekey) {
        display.value = citekey.citekey;
        return display.classList[citekey.citekeyFormat ? 'add' : 'remove']('citekey-dynamic');
      } else {
        display.value = '';
        if (!citekey) {
          return Zotero.BetterBibTeX.log(item.itemTypeID + " has no citekey");
        }
      }
    }
  };
})(ZoteroItemPane.viewItem);
