// Generated by CoffeeScript 1.10.0
Components.utils["import"]("resource://zotero/config.js");

if (!ZoteroPane_Local.BetterBibTeX) {
  ZoteroPane_Local.BetterBibTeX = {
    serverURL: function(extension) {
      var collection, collectionsView, err, error, itemGroup, libid, ref, ref1, serverPort, url;
      collectionsView = (ref = Zotero.getActiveZoteroPane()) != null ? ref.collectionsView : void 0;
      itemGroup = collectionsView != null ? collectionsView._getItemAtRow((ref1 = collectionsView.selection) != null ? ref1.currentIndex : void 0) : void 0;
      if (!itemGroup) {
        return;
      }
      try {
        serverPort = Zotero.Prefs.get('httpServer.port');
      } catch (error) {
        err = error;
        return;
      }
      if (itemGroup.isCollection()) {
        collection = collectionsView.getSelectedCollection();
        url = "collection?/" + (collection.libraryID || 0) + "/" + (collection.key + extension);
      }
      if (itemGroup.isLibrary(true)) {
        libid = collectionsView.getSelectedLibraryID();
        url = libid ? "library?/" + libid + "/library" + extension : "library?library" + extension;
      }
      if (!url) {
        return;
      }
      return "http://localhost:" + serverPort + "/better-bibtex/" + url;
    }
  };
  ZoteroPane_Local.buildCollectionContextMenu = (function(original) {
    return function() {
      var i, id, itemGroup, len, menuItem, ref, zv;
      zv = ZOTERO_CONFIG.VERSION.split('.');
      if (parseInt(zv[0]) >= 4 && parseInt(zv[1]) === 0 && parseInt(zv[1]) <= 26) {
        itemGroup = this.collectionsView._getItemAtRow(this.collectionsView.selection.currentIndex);
        menuItem = this.document.getElementById('zotero-better-bibtex-export-group');
        menuItem.setAttribute('disabled', false);
        menuItem.setAttribute('hidden', !itemGroup.isGroup());
      }
      ref = ['zotero-better-bibtex-show-export-url', 'zotero-better-bibtex-report-errors'];
      for (i = 0, len = ref.length; i < len; i++) {
        id = ref[i];
        menuItem = this.document.getElementById(id);
        menuItem.setAttribute('disabled', false);
        menuItem.setAttribute('hidden', !(itemGroup.isLibrary(true) || itemGroup.isCollection()));
      }
      menuItem = this.document.getElementById('zotero-better-bibtex-collectionmenu-separator');
      menuItem.setAttribute('hidden', !(itemGroup.isLibrary(true) || itemGroup.isCollection()));
      return original.apply(this, arguments);
    };
  })(ZoteroPane_Local.buildCollectionContextMenu);
}

if (!Zotero_File_Interface.BetterBibTeX) {
  Zotero_File_Interface.BetterBibTeX = true;
  Zotero_File_Interface.exportCollection = (function(original) {
    return function() {
      var exporter, search;
      if (ZoteroPane_Local.getSelectedCollection() || !(search = ZoteroPane_Local.getSelectedSavedSearch())) {
        return original.apply(this, arguments);
      }
      exporter = new Zotero_File_Exporter();
      exporter.items = {
        objectType: 'saved-search',
        search: search,
        items: ZoteroPane_Local.getSortedItems()
      };
      if (!exporter.items.items) {
        throw new Error('No items to save');
      }
      exporter.name = search.name;
      return exporter.save();
    };
  })(Zotero_File_Interface.exportCollection);
}
